### ISSUE TITLE
SITA Workshop Activity

### ISSUE THREAD

**Issue by ainsofs** [sita-samoa/sita-membership#289]
This is a placeholder issue for use during the SITA Workshop on Contributing to Open source.

Add a comment to this issue to indicate how you think you might contribute to the project.

Slides: https://1drv.ms/p/c/91513ada79c70eb8/EWrleGHvAaxPhbI4hYnXMNwBTQcWRnDT9ajaI38VdRPb1Q?e=eY3bp1

**Comment by Green-Ranger11** [comment]
I can contribute to the front end

**Comment by sweetrush** [comment]
I can help writing some documentations

**Comment by genebarker** [comment]
Maybe improve instructions to make easier to use.

**Comment by samoankid** [comment]
I can contribute with documentations and analysis.

**Comment by samsonsamoa** [comment]
I'll bring pop-corn

**Comment by samoankid** [comment]
Some soft drinks for the team..

**Comment by story98** [comment]
I can help promote our open source to various platforms/organisation.

**Comment by tomashee** [comment]
Can I tattoo your branch?

**Comment by kashi4987** [comment]
I got Sula porkbun solutions

**Comment by RaeRae2020** [comment]
I can contribute to design side of things maybe idk

**Comment by story98** [comment]
Siga free wifi plan from Vodafone yessir

**Comment by tintam685** [comment]
hello Group 3

**Comment by CyberSimbax** [comment]
I can share the wifi password: VFSamo@RoomA

**Comment by ilu73** [comment]
I can pray for the success of this project. Infact I just did.

**Comment by ainsofs** [comment]
> Siga free wifi plan from Vodafone yessir

Lea e maua le free Wifi ole conference room 😆

**Comment by laa1213** [comment]
👌😘

**Comment by samoankid** [comment]
> I can share the wifi password: VFSamo@RoomA

Thank You Sir

**Comment by Tauruxic-Code** [comment]
I can add some comments :)

**Comment by SLeota24** [comment]
Got some kekebun

**Comment by ainsofs** [comment]
Malo everyone and thanks again for participating in the workshop. I released a new version of the SITA platform today which includes your contributions. Looking forward to seeing more contributions from you.

https://github.com/sita-samoa/sita-membership/releases/tag/v0.6.1-beta

Cheers,
